language: generic

os:
  - linux
  - osx

env:
  matrix:
    - DB=sqlite3 PHARO_VERSION=50
    - DB=sqlite3 PHARO_VERSION=60


addons:
  apt:
    packages:
    - lib32asound2
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
    - libsqlite3-0:i386

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get autoremove sqlite3;
        sudo apt-add-repository -y ppa:travis-ci/sqlite3;
        sudo apt-get -y update;
        sudo apt-cache show sqlite3;
        sudo apt-get install sqlite3=3.7.15.1-1~travis1;
        sudo sqlite3 -version;
    fi;

install:
  # We prepare SQLITE, Pharo and garage packages
  - ln -s /usr/lib/i386-linux-gnu/libsqlite3.so.0 libsqlite3
  - wget -O - get.pharo.org/${PHARO_VERSION}+vm | bash
  - ./scripts/install-packages.sh DB

before_script:
  - ./pharo Pharo.image eval --save "GAContinuousIntegrationConfiguration new configureSqlite3"

script:
  - ./pharo Pharo.image test --no-xterm --fail-on-failure "Garage.*"